name: NPM Publish

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  NODE_VERSION: 16
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      # This is needed for Python 3.12+, since many versions of node-gyp
      # are incompatible with Python 3.12+, which no-longer ships 'distutils'
      # out of the box. 'setuptools' package provides 'distutils'.
      - run: python3 -m pip install --break-system-packages setuptools
      - run: npm ci
      - run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
