name: Test

on:
  pull_request:
  push:
    branches: [ 'master' ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest, windows-2019 ]
        node-version: [ 16, 18 ]
      fail-fast: false
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # Make sure we get all commits, since testing uses the local git info
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Latest npm
      run: npm install -g npm
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm run test
